project_name: tenki
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
brews:
  -
    tap:
      owner: mmmommm
      name: homebrew-tenki
    description: Returns weather forecast in perticular prefecture. 
    homepage: "https://github.com/mmmommm/tenki"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    install: |
      bin.install Dir['tenki']