version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    working_directory: ~/tenki
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: env作成
          command: |
            make build
      - run:
          name: goreleaser動かす
          command: |
            curl -sL https://git.io/goreleaser | bash